[package]
name = "minnal-build-support"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
minnal-core = { path = "../minnal-core" }
minnal-selfdev-types = { path = "../minnal-selfdev-types" }
minnal-storage = { path = "../minnal-storage" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"

[dev-dependencies]
tempfile = "3"
